### ISSUE TITLE
Feature request: Widget

### ISSUE THREAD

**Issue by biuklija** [vbresan/eurokonverter_android#2]
Izvrsna aplikacija, predlažem da joj dodate funkcionalnost widgeta kako bi se mogla dodati na početni zaslon za brži pristup kalkulatoru.

**Comment by vbresan** [comment]
Na žalost widgeti, sami po sebi, ne podržavaju komponente sa editabilnim tekstom (EditText). Tome se može doskočiti, ali rješenje nije trivijalno. Premda predstavlja izazov, trenutno nisam siguran da li bi se upuštao u to. Ipak se radi o 'nice to have', a ne ključnoj funkcionalnosti u ne-komercijalnoj aplikaciji ograničenog vijeka.

**Comment by biuklija** [comment]
[Ovaj kalkulator](https://github.com/SimpleMobileTools/Simple-Calculator) to ima riješeno preko tipkovnice i jednog polja koje se editira s unaprijed postavljenim fokusom. Možda nešto takvo u kombinaciji s tipkom za izbor gornje ili donje vrijednosti?

**Comment by vbresan** [comment]
Predloženi widget je praktički ponavljanje kompletnog sučelja aplikacije, ali smanjenih dimenzija. Ne vidim smisla u implementaciji nečeg takvog samo da bi se korisniku uštedio jedan touch potreban za pokretanje aplikacije.

Pokušati ću implementirati widget kako spada AKO broj aktivnih korisnika aplikacije pređe 10,000. Trenutno ih je 9,730.

**Comment by vbresan** [comment]
Ne stignem implementirati widget. Ako se netko želi okušati - slobodno.
