### ISSUE TITLE
EUR polje kao predodabrano

### ISSUE THREAD

**Issue by biuklija** [vbresan/eurokonverter_android#3]
Kako je nakon prelaska na euro korisnicima u većini slučajeva potrebnija konverzija EUR > HRK, je li moguće zamijeniti redoslijed valuta na početnom zaslonu ili po pokretanju aplikacije predodabrati donje polje (EUR)? 
Možda kao opcija za konfiguraciju ili pamćenje zadnjeg odabranog polja kod novog pokretanja?

**Comment by vbresan** [comment]
Evo, uštedio sam vam jedan touch. 

Implementirano u verziji 2.0.3. Pojavit će se u Google Play Store-u nakon što je odobre, a na f-droidu nakon što je buildaju.

Zamjena redoslijeda nije dolazila u obzir s obzirom da se narušava UI na koji su korisnici već naviknuti. Također, ovako jednostavnu aplikaciju ne mislim komplicirati sa pamćenjem konfiguracije.
